Dev fix bookmark
project-violet/violet pull request #294
Opened 2023-12-31 03:14 UTC by TaYaKi71751

https://github.com/project-violet/violet/pull/292

2023-12-31 03:57 UTC, violet-dev requested changes

2023-12-31 03:57 UTC, violet-dev commented on lib/pages/bookmark/group/group_article_list_page.dart
> +      _rebuild();
이 부분은 forEach 바깥에 있어야 합니다.

2023-12-31 03:57 UTC, violet-dev commented on lib/network/libcurl.dart
> +class Http3Request {
http/3 기능을 추가하신 이유가 있나요?

2023-12-31 03:57 UTC, violet-dev commented on lib/pages/bookmark/group/group_article_list_page.dart
>      };
```suggestion
    final article = EHParser.parseArticleData(html);
    final meta = {
      'Id': int.parse(id),
      'EHash': hash,
      'Title': article.title,
      'Artists': article.artist?.join('|') ?? 'N/A',
      'Language':
          article.languages?.join('|') ?? article.language.trim().toLowerCase(),
      'Tags': ((article.female?.map((e) => 'female:$e').toList() ?? []) +
              (article.male?.map((e) => 'male:$e').toList() ?? []) +
              (article.misc?.map((e) => 'tag:$e').toList() ?? []))
          .join('|'),
      'Characters': article.character?.join('|') ?? '',
      'Type': article.type,
      'Series': article.parody?.join('|') ?? '',
    };
```

2023-12-31 03:57 UTC, violet-dev commented on lib/pages/bookmark/group/group_article_list_page.dart
>      };
```suggestion
    final article = EHParser.parseArticleData(html);
    final meta = {
      'Id': int.parse(id),
      'EHash': hash,
      'Title': article.title,
      'Artists': article.artist?.join('|') ?? 'N/A',
      'Language':
          article.languages?.join('|') ?? article.language.trim().toLowerCase(),
      'Tags': ((article.female?.map((e) => 'female:$e').toList() ?? []) +
              (article.male?.map((e) => 'male:$e').toList() ?? []) +
              (article.misc?.map((e) => 'tag:$e').toList() ?? []))
          .join('|'),
      'Characters': article.character?.join('|') ?? '',
      'Type': article.type,
      'Series': article.parody?.join('|') ?? '',
    };
```

QueryResult에 From EHArticle 메서드를 만들어도 좋을 것 같네요

2023-12-31 03:57 UTC, violet-dev commented on lib/pages/bookmark/group/group_article_list_page.dart
> +        _rebuild();
위 코멘트와 마찬가지로 이 부분이 loop내에 있으면 안됩니다.

2023-12-31 03:57 UTC, violet-dev commented on lib/database/query.dart
> +
query 모양과 다르기 때문에 boolean값으로 빼면 좋을 것 같습니다.

2023-12-31 04:24 UTC, TaYaKi71751 commented on lib/pages/bookmark/group/group_article_list_page.dart
> +      _rebuild();
바깥에 있는 경우 적용이 되지 않았습니다.

2023-12-31 04:26 UTC, TaYaKi71751 commented on lib/network/libcurl.dart
> +class Http3Request {
일부 Connection reset by peer 문제가 해결 되었습니다.

2023-12-31 04:31 UTC, violet-dev commented on lib/network/libcurl.dart
> +class Http3Request {
혹시 [cronet_http](https://github.com/dart-lang/http/tree/master/pkgs/cronet_http), [cupertino_http](https://github.com/dart-lang/http/tree/master/pkgs/cupertino_http)를 고려해보셨나요?

2023-12-31 04:36 UTC, TaYaKi71751 commented on lib/pages/bookmark/group/group_article_list_page.dart
> +        _rebuild();
async 루프 밖에 있기 위해서는 루프 가 끝나고 적용이 되어야 합니다.
- 위 부분이 루프 밖에 있고, Future.forEach를 사용하는 경우 
> 모든 아티클이 불러와지기 전에는 빈 화면(로딩 스크린이 없음)만 보여지게 됩니다.
- 위 부분이 루프 밖에 있고, `articleList.forEach((element) async { /* 코드 */ }); /* 위 부분 */` 형태로 되는 경우
> 위 부분이 먼저 실행되고 async루프가 나중에 실행되었습니다.
해결방안으로
- 1. async 루프가 시작되기 전에 북마크 갯수만큼 리스트를 추가 후 리빌드
- 2. async 루프마다 위 부분을 추가하여 로드 되는 즉시 리빌드
를 적용 하였습니다.

2024-01-01 01:59 UTC, TaYaKi71751 commented
다음과 같이 수정한 경우 
![image](https://github.com/project-violet/violet/assets/56256195/a3a3d36f-4062-47ad-8a39-a639b44efcab)
![image](https://github.com/project-violet/violet/assets/56256195/3829cc6a-1b03-44d3-8761-8a4e1d6b6935)
정보가 뜨지 않았습니다.
![image](https://github.com/project-violet/violet/assets/56256195/6f618791-560f-4c9b-99cd-d399f748f551)

2024-01-01 04:27 UTC, TaYaKi71751 commented
혹시 upstream으로 부터 새로 시작하여도 괜찮을까요

2024-01-01 05:58 UTC, TaYaKi71751 commented
다른 pr로 넘어가겠습니다.

2024-01-01 05:58 UTC, closed without merging

2024-01-01 12:30 UTC, violet-dev commented
@TaYaKi71751 혹시 계속 진행하실 예정인가요? 아니라면 제가 https://github.com/project-violet/violet/pull/294#discussion_r1438810667 와 같이 살펴보겠습니다.

2024-01-01 13:22 UTC, TaYaKi71751 commented
> @TaYaKi71751 혹시 계속 진행하실 예정인가요? 아니라면 제가 [#294 (comment)](https://github.com/project-violet/violet/pull/294#discussion_r1438810667) 와 같이 살펴보겠습니다.

현재 진행할 예정은 없습니다.